python3 insertSamples.py 1 1
python3 insertSamples.py 1 2
python3 insertSamples.py 1 3
python3 insertSamples.py 2 1
python3 insertSamples.py 2 2
python3 insertSamples.py 2 3
python3 insertSamplesFromTrack.py 3 1
python3 insertSamplesFromTrack.py 3 2
python3 insertSamplesFromTrack.py 3 3
